### ISSUE TITLE
Exclude region list

### ISSUE THREAD

**Issue by TonyKess** [KiddLab/QuicK-mer2#2]
Hello,

I attempted the "exclude regions" option using the -c flag with a bed file extracted from the .fai file for my reference genome to remove unplaced contigs. I'm finding that during the intiial kmer search step, these sites are not being excluded, and their full titles from the reference genome  (including information on the sample itself) are being used. Any idea how to fix this issue?

Thanks,

Tony

**Comment by jmkidd** [comment]
Hi, quicKmer2 search will consider every k-mer in the given reference fasta sequence.  The -c option gives regions that are excluded during GC and copy-number normalization, typically known duplications and CNVs.   K-mers in those regions are still considered and analyzed.  I agree that it is probably good to exclude unplaced contigs from the normalization since such sequences are often duplicated. 

Since the unplaced contigs are part of the reference I would keep them in the kmer dataset for most applications.  If you want to omit them for some reason then you will have to remove them from the initial fasta sequence. 

Hope this helps answer your question.  If not, I might be able to help with some more information about what you are trying.

**Comment by TonyKess** [comment]
This helps, thanks! I'll move forward with analyzing my data with the intact reference genome and then restrict interpretation to the final .bed files.
